const FETCH_POST = 'FETCH_POST';
const NEW_POST = 'NEW_POST';
const EDIT_POST = 'EDIT_POST';
const UPDATE_POST_FIELD = 'UPDATE_POST_FIELD';
const RESET_POST = 'RESET_POST';
const DELETE_POST = 'DELETE_POST';

export { FETCH_POST, NEW_POST, EDIT_POST, UPDATE_POST_FIELD, RESET_POST, DELETE_POST };